package com.xyt.usermucon.dao.power;

import com.xyt.usermucon.dto.power.SysPowerinfo;
import com.xyt.usermucon.dto.power.SysPowerinfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SysPowerinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    long countByExample(SysPowerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    int deleteByExample(SysPowerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    int insert(SysPowerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    int insertSelective(SysPowerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    List<SysPowerinfo> selectByExample(SysPowerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    SysPowerinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysPowerinfo record, @Param("example") SysPowerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    int updateByExample(@Param("record") SysPowerinfo record, @Param("example") SysPowerinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    int updateByPrimaryKeySelective(SysPowerinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_powerinfo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    int updateByPrimaryKey(SysPowerinfo record);

    /**
     * 查询该子菜单名称的数量
     * @param powerName
     * @return
     */
    Integer queryPowerCountByName(String powerName);
    /**
     * 全查询子菜单
     * @param sysPowerinfo
     * @return
     */
    List<SysPowerinfo> selectSysPowerinfo(SysPowerinfo sysPowerinfo);
}