package com.xyt.usermucon.dao.power;

import com.xyt.usermucon.dto.power.SysSystemname;
import com.xyt.usermucon.dto.power.SysSystemnameExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface SysSystemnameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    long countByExample(SysSystemnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    int deleteByExample(SysSystemnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    int insert(SysSystemname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    int insertSelective(SysSystemname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    List<SysSystemname> selectByExample(SysSystemnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    SysSystemname selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysSystemname record, @Param("example") SysSystemnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    int updateByExample(@Param("record") SysSystemname record, @Param("example") SysSystemnameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    int updateByPrimaryKeySelective(SysSystemname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    int updateByPrimaryKey(SysSystemname record);

    /**
     * 查询该系统名称的数量
     * @param systemname
     * @return
     */
    Integer querySystemCountByName(String systemname);
}