package com.xyt.usermucon.dto.power;

import java.util.List;

public class SysGroupinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_groupinfo.id
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    private String id;
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_groupinfo.groupName
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_groupinfo.systemName
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    private String systemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_groupinfo.picPath
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    private String picpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_groupinfo.picName
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    private String picname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_groupinfo.isExpand
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    private Boolean isexpand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_groupinfo.sortNo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    private Integer sortno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_groupinfo.remark
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    private String remark;

    private List<SysPowerinfo> sysPowerinfo;
    private String searchName;

    public List<SysPowerinfo> getSysPowerinfo() {
        return sysPowerinfo;
    }

    public void setSysPowerinfo(List<SysPowerinfo> sysPowerinfo) {
        this.sysPowerinfo = sysPowerinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_groupinfo.id
     *
     * @return the value of sys_groupinfo.id
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_groupinfo.id
     *
     * @param id the value for sys_groupinfo.id
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_groupinfo.groupName
     *
     * @return the value of sys_groupinfo.groupName
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_groupinfo.groupName
     *
     * @param groupname the value for sys_groupinfo.groupName
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_groupinfo.systemName
     *
     * @return the value of sys_groupinfo.systemName
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public String getSystemname() {
        return systemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_groupinfo.systemName
     *
     * @param systemname the value for sys_groupinfo.systemName
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public void setSystemname(String systemname) {
        this.systemname = systemname == null ? null : systemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_groupinfo.picPath
     *
     * @return the value of sys_groupinfo.picPath
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public String getPicpath() {
        return picpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_groupinfo.picPath
     *
     * @param picpath the value for sys_groupinfo.picPath
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public void setPicpath(String picpath) {
        this.picpath = picpath == null ? null : picpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_groupinfo.picName
     *
     * @return the value of sys_groupinfo.picName
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public String getPicname() {
        return picname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_groupinfo.picName
     *
     * @param picname the value for sys_groupinfo.picName
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public void setPicname(String picname) {
        this.picname = picname == null ? null : picname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_groupinfo.isExpand
     *
     * @return the value of sys_groupinfo.isExpand
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public Boolean getIsexpand() {
        return isexpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_groupinfo.isExpand
     *
     * @param isexpand the value for sys_groupinfo.isExpand
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public void setIsexpand(Boolean isexpand) {
        this.isexpand = isexpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_groupinfo.sortNo
     *
     * @return the value of sys_groupinfo.sortNo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public Integer getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_groupinfo.sortNo
     *
     * @param sortno the value for sys_groupinfo.sortNo
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public void setSortno(Integer sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_groupinfo.remark
     *
     * @return the value of sys_groupinfo.remark
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_groupinfo.remark
     *
     * @param remark the value for sys_groupinfo.remark
     *
     * @mbg.generated Thu Sep 05 09:30:25 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getSearchName() {
        return searchName;
    }

    public void setSearchName(String searchName) {
        this.searchName = searchName;
    }
}