package com.xyt.usermucon.dto.power;

public class SysRoleinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roleinfo.id
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roleinfo.roleName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roleinfo.systemName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String systemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roleinfo.sortNo
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private Integer sortno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roleinfo.remark
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roleinfo.id
     *
     * @return the value of sys_roleinfo.id
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roleinfo.id
     *
     * @param id the value for sys_roleinfo.id
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roleinfo.roleName
     *
     * @return the value of sys_roleinfo.roleName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roleinfo.roleName
     *
     * @param rolename the value for sys_roleinfo.roleName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roleinfo.systemName
     *
     * @return the value of sys_roleinfo.systemName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getSystemname() {
        return systemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roleinfo.systemName
     *
     * @param systemname the value for sys_roleinfo.systemName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setSystemname(String systemname) {
        this.systemname = systemname == null ? null : systemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roleinfo.sortNo
     *
     * @return the value of sys_roleinfo.sortNo
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public Integer getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roleinfo.sortNo
     *
     * @param sortno the value for sys_roleinfo.sortNo
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setSortno(Integer sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roleinfo.remark
     *
     * @return the value of sys_roleinfo.remark
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roleinfo.remark
     *
     * @param remark the value for sys_roleinfo.remark
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}