package com.xyt.usermucon.dto.power;

import java.util.List;

public class SysSystemname {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.id
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.systemName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String systemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.systemContent
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String systemcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.versionNo
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String versionno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.enabledPicName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String enabledpicname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.disabledPicName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String disabledpicname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.picUrl
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String picurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.sortNo
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private Integer sortno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.initPage
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String initpage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_systemname.remark
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    private String remark;
    private List<SysGroupinfo> list;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.id
     *
     * @return the value of sys_systemname.id
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.id
     *
     * @param id the value for sys_systemname.id
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.systemName
     *
     * @return the value of sys_systemname.systemName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getSystemname() {
        return systemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.systemName
     *
     * @param systemname the value for sys_systemname.systemName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setSystemname(String systemname) {
        this.systemname = systemname == null ? null : systemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.systemContent
     *
     * @return the value of sys_systemname.systemContent
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getSystemcontent() {
        return systemcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.systemContent
     *
     * @param systemcontent the value for sys_systemname.systemContent
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setSystemcontent(String systemcontent) {
        this.systemcontent = systemcontent == null ? null : systemcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.versionNo
     *
     * @return the value of sys_systemname.versionNo
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getVersionno() {
        return versionno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.versionNo
     *
     * @param versionno the value for sys_systemname.versionNo
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setVersionno(String versionno) {
        this.versionno = versionno == null ? null : versionno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.enabledPicName
     *
     * @return the value of sys_systemname.enabledPicName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getEnabledpicname() {
        return enabledpicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.enabledPicName
     *
     * @param enabledpicname the value for sys_systemname.enabledPicName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setEnabledpicname(String enabledpicname) {
        this.enabledpicname = enabledpicname == null ? null : enabledpicname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.disabledPicName
     *
     * @return the value of sys_systemname.disabledPicName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getDisabledpicname() {
        return disabledpicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.disabledPicName
     *
     * @param disabledpicname the value for sys_systemname.disabledPicName
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setDisabledpicname(String disabledpicname) {
        this.disabledpicname = disabledpicname == null ? null : disabledpicname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.picUrl
     *
     * @return the value of sys_systemname.picUrl
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.picUrl
     *
     * @param picurl the value for sys_systemname.picUrl
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.sortNo
     *
     * @return the value of sys_systemname.sortNo
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public Integer getSortno() {
        return sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.sortNo
     *
     * @param sortno the value for sys_systemname.sortNo
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setSortno(Integer sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.initPage
     *
     * @return the value of sys_systemname.initPage
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getInitpage() {
        return initpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.initPage
     *
     * @param initpage the value for sys_systemname.initPage
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setInitpage(String initpage) {
        this.initpage = initpage == null ? null : initpage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_systemname.remark
     *
     * @return the value of sys_systemname.remark
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_systemname.remark
     *
     * @param remark the value for sys_systemname.remark
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public List<SysGroupinfo> getList() {
        return list;
    }

    public void setList(List<SysGroupinfo> list) {
        this.list = list;
    }

    @Override
    public String toString() {
        return "SysSystemname{" +
                "id='" + id + '\'' +
                ", systemname='" + systemname + '\'' +
                ", systemcontent='" + systemcontent + '\'' +
                ", versionno='" + versionno + '\'' +
                ", enabledpicname='" + enabledpicname + '\'' +
                ", disabledpicname='" + disabledpicname + '\'' +
                ", picurl='" + picurl + '\'' +
                ", sortno=" + sortno +
                ", initpage='" + initpage + '\'' +
                ", remark='" + remark + '\'' +
                ", list=" + list +
                '}';
    }
}