package com.xyt.usermucon.dto.power;

import java.util.ArrayList;
import java.util.List;

public class SysSystemnameExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public SysSystemnameExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemnameIsNull() {
            addCriterion("systemName is null");
            return (Criteria) this;
        }

        public Criteria andSystemnameIsNotNull() {
            addCriterion("systemName is not null");
            return (Criteria) this;
        }

        public Criteria andSystemnameEqualTo(String value) {
            addCriterion("systemName =", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotEqualTo(String value) {
            addCriterion("systemName <>", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameGreaterThan(String value) {
            addCriterion("systemName >", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameGreaterThanOrEqualTo(String value) {
            addCriterion("systemName >=", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLessThan(String value) {
            addCriterion("systemName <", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLessThanOrEqualTo(String value) {
            addCriterion("systemName <=", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameLike(String value) {
            addCriterion("systemName like", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotLike(String value) {
            addCriterion("systemName not like", value, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameIn(List<String> values) {
            addCriterion("systemName in", values, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotIn(List<String> values) {
            addCriterion("systemName not in", values, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameBetween(String value1, String value2) {
            addCriterion("systemName between", value1, value2, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemnameNotBetween(String value1, String value2) {
            addCriterion("systemName not between", value1, value2, "systemname");
            return (Criteria) this;
        }

        public Criteria andSystemcontentIsNull() {
            addCriterion("systemContent is null");
            return (Criteria) this;
        }

        public Criteria andSystemcontentIsNotNull() {
            addCriterion("systemContent is not null");
            return (Criteria) this;
        }

        public Criteria andSystemcontentEqualTo(String value) {
            addCriterion("systemContent =", value, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentNotEqualTo(String value) {
            addCriterion("systemContent <>", value, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentGreaterThan(String value) {
            addCriterion("systemContent >", value, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentGreaterThanOrEqualTo(String value) {
            addCriterion("systemContent >=", value, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentLessThan(String value) {
            addCriterion("systemContent <", value, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentLessThanOrEqualTo(String value) {
            addCriterion("systemContent <=", value, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentLike(String value) {
            addCriterion("systemContent like", value, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentNotLike(String value) {
            addCriterion("systemContent not like", value, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentIn(List<String> values) {
            addCriterion("systemContent in", values, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentNotIn(List<String> values) {
            addCriterion("systemContent not in", values, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentBetween(String value1, String value2) {
            addCriterion("systemContent between", value1, value2, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andSystemcontentNotBetween(String value1, String value2) {
            addCriterion("systemContent not between", value1, value2, "systemcontent");
            return (Criteria) this;
        }

        public Criteria andVersionnoIsNull() {
            addCriterion("versionNo is null");
            return (Criteria) this;
        }

        public Criteria andVersionnoIsNotNull() {
            addCriterion("versionNo is not null");
            return (Criteria) this;
        }

        public Criteria andVersionnoEqualTo(String value) {
            addCriterion("versionNo =", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoNotEqualTo(String value) {
            addCriterion("versionNo <>", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoGreaterThan(String value) {
            addCriterion("versionNo >", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoGreaterThanOrEqualTo(String value) {
            addCriterion("versionNo >=", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoLessThan(String value) {
            addCriterion("versionNo <", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoLessThanOrEqualTo(String value) {
            addCriterion("versionNo <=", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoLike(String value) {
            addCriterion("versionNo like", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoNotLike(String value) {
            addCriterion("versionNo not like", value, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoIn(List<String> values) {
            addCriterion("versionNo in", values, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoNotIn(List<String> values) {
            addCriterion("versionNo not in", values, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoBetween(String value1, String value2) {
            addCriterion("versionNo between", value1, value2, "versionno");
            return (Criteria) this;
        }

        public Criteria andVersionnoNotBetween(String value1, String value2) {
            addCriterion("versionNo not between", value1, value2, "versionno");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameIsNull() {
            addCriterion("enabledPicName is null");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameIsNotNull() {
            addCriterion("enabledPicName is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameEqualTo(String value) {
            addCriterion("enabledPicName =", value, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameNotEqualTo(String value) {
            addCriterion("enabledPicName <>", value, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameGreaterThan(String value) {
            addCriterion("enabledPicName >", value, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameGreaterThanOrEqualTo(String value) {
            addCriterion("enabledPicName >=", value, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameLessThan(String value) {
            addCriterion("enabledPicName <", value, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameLessThanOrEqualTo(String value) {
            addCriterion("enabledPicName <=", value, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameLike(String value) {
            addCriterion("enabledPicName like", value, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameNotLike(String value) {
            addCriterion("enabledPicName not like", value, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameIn(List<String> values) {
            addCriterion("enabledPicName in", values, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameNotIn(List<String> values) {
            addCriterion("enabledPicName not in", values, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameBetween(String value1, String value2) {
            addCriterion("enabledPicName between", value1, value2, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andEnabledpicnameNotBetween(String value1, String value2) {
            addCriterion("enabledPicName not between", value1, value2, "enabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameIsNull() {
            addCriterion("disabledPicName is null");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameIsNotNull() {
            addCriterion("disabledPicName is not null");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameEqualTo(String value) {
            addCriterion("disabledPicName =", value, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameNotEqualTo(String value) {
            addCriterion("disabledPicName <>", value, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameGreaterThan(String value) {
            addCriterion("disabledPicName >", value, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameGreaterThanOrEqualTo(String value) {
            addCriterion("disabledPicName >=", value, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameLessThan(String value) {
            addCriterion("disabledPicName <", value, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameLessThanOrEqualTo(String value) {
            addCriterion("disabledPicName <=", value, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameLike(String value) {
            addCriterion("disabledPicName like", value, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameNotLike(String value) {
            addCriterion("disabledPicName not like", value, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameIn(List<String> values) {
            addCriterion("disabledPicName in", values, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameNotIn(List<String> values) {
            addCriterion("disabledPicName not in", values, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameBetween(String value1, String value2) {
            addCriterion("disabledPicName between", value1, value2, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andDisabledpicnameNotBetween(String value1, String value2) {
            addCriterion("disabledPicName not between", value1, value2, "disabledpicname");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNull() {
            addCriterion("picUrl is null");
            return (Criteria) this;
        }

        public Criteria andPicurlIsNotNull() {
            addCriterion("picUrl is not null");
            return (Criteria) this;
        }

        public Criteria andPicurlEqualTo(String value) {
            addCriterion("picUrl =", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotEqualTo(String value) {
            addCriterion("picUrl <>", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThan(String value) {
            addCriterion("picUrl >", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlGreaterThanOrEqualTo(String value) {
            addCriterion("picUrl >=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThan(String value) {
            addCriterion("picUrl <", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLessThanOrEqualTo(String value) {
            addCriterion("picUrl <=", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlLike(String value) {
            addCriterion("picUrl like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotLike(String value) {
            addCriterion("picUrl not like", value, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlIn(List<String> values) {
            addCriterion("picUrl in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotIn(List<String> values) {
            addCriterion("picUrl not in", values, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlBetween(String value1, String value2) {
            addCriterion("picUrl between", value1, value2, "picurl");
            return (Criteria) this;
        }

        public Criteria andPicurlNotBetween(String value1, String value2) {
            addCriterion("picUrl not between", value1, value2, "picurl");
            return (Criteria) this;
        }

        public Criteria andSortnoIsNull() {
            addCriterion("sortNo is null");
            return (Criteria) this;
        }

        public Criteria andSortnoIsNotNull() {
            addCriterion("sortNo is not null");
            return (Criteria) this;
        }

        public Criteria andSortnoEqualTo(Integer value) {
            addCriterion("sortNo =", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoNotEqualTo(Integer value) {
            addCriterion("sortNo <>", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoGreaterThan(Integer value) {
            addCriterion("sortNo >", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("sortNo >=", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoLessThan(Integer value) {
            addCriterion("sortNo <", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoLessThanOrEqualTo(Integer value) {
            addCriterion("sortNo <=", value, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoIn(List<Integer> values) {
            addCriterion("sortNo in", values, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoNotIn(List<Integer> values) {
            addCriterion("sortNo not in", values, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoBetween(Integer value1, Integer value2) {
            addCriterion("sortNo between", value1, value2, "sortno");
            return (Criteria) this;
        }

        public Criteria andSortnoNotBetween(Integer value1, Integer value2) {
            addCriterion("sortNo not between", value1, value2, "sortno");
            return (Criteria) this;
        }

        public Criteria andInitpageIsNull() {
            addCriterion("initPage is null");
            return (Criteria) this;
        }

        public Criteria andInitpageIsNotNull() {
            addCriterion("initPage is not null");
            return (Criteria) this;
        }

        public Criteria andInitpageEqualTo(String value) {
            addCriterion("initPage =", value, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageNotEqualTo(String value) {
            addCriterion("initPage <>", value, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageGreaterThan(String value) {
            addCriterion("initPage >", value, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageGreaterThanOrEqualTo(String value) {
            addCriterion("initPage >=", value, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageLessThan(String value) {
            addCriterion("initPage <", value, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageLessThanOrEqualTo(String value) {
            addCriterion("initPage <=", value, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageLike(String value) {
            addCriterion("initPage like", value, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageNotLike(String value) {
            addCriterion("initPage not like", value, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageIn(List<String> values) {
            addCriterion("initPage in", values, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageNotIn(List<String> values) {
            addCriterion("initPage not in", values, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageBetween(String value1, String value2) {
            addCriterion("initPage between", value1, value2, "initpage");
            return (Criteria) this;
        }

        public Criteria andInitpageNotBetween(String value1, String value2) {
            addCriterion("initPage not between", value1, value2, "initpage");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_systemname
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 04 14:40:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_systemname
     *
     * @mbg.generated Wed Sep 04 14:40:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}