package com.xyt.usermucon.dto.power;

import java.util.Date;

public class SysUserinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.id
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.deptId
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.username
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.password
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.name
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.englishName
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String englishname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.portrait
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.mobile
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.tel
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.qq
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.email
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.address
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.postCode
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.userType
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.createTime
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.stopSign
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private Boolean stopsign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userinfo.remark
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.id
     *
     * @return the value of sys_userinfo.id
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.id
     *
     * @param id the value for sys_userinfo.id
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.deptId
     *
     * @return the value of sys_userinfo.deptId
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.deptId
     *
     * @param deptid the value for sys_userinfo.deptId
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.username
     *
     * @return the value of sys_userinfo.username
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.username
     *
     * @param username the value for sys_userinfo.username
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.password
     *
     * @return the value of sys_userinfo.password
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.password
     *
     * @param password the value for sys_userinfo.password
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.name
     *
     * @return the value of sys_userinfo.name
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.name
     *
     * @param name the value for sys_userinfo.name
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.englishName
     *
     * @return the value of sys_userinfo.englishName
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getEnglishname() {
        return englishname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.englishName
     *
     * @param englishname the value for sys_userinfo.englishName
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setEnglishname(String englishname) {
        this.englishname = englishname == null ? null : englishname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.portrait
     *
     * @return the value of sys_userinfo.portrait
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.portrait
     *
     * @param portrait the value for sys_userinfo.portrait
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait == null ? null : portrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.mobile
     *
     * @return the value of sys_userinfo.mobile
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.mobile
     *
     * @param mobile the value for sys_userinfo.mobile
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.tel
     *
     * @return the value of sys_userinfo.tel
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.tel
     *
     * @param tel the value for sys_userinfo.tel
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.qq
     *
     * @return the value of sys_userinfo.qq
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.qq
     *
     * @param qq the value for sys_userinfo.qq
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.email
     *
     * @return the value of sys_userinfo.email
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.email
     *
     * @param email the value for sys_userinfo.email
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.address
     *
     * @return the value of sys_userinfo.address
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.address
     *
     * @param address the value for sys_userinfo.address
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.postCode
     *
     * @return the value of sys_userinfo.postCode
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.postCode
     *
     * @param postcode the value for sys_userinfo.postCode
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.userType
     *
     * @return the value of sys_userinfo.userType
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.userType
     *
     * @param usertype the value for sys_userinfo.userType
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.createTime
     *
     * @return the value of sys_userinfo.createTime
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.createTime
     *
     * @param createtime the value for sys_userinfo.createTime
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.stopSign
     *
     * @return the value of sys_userinfo.stopSign
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public Boolean getStopsign() {
        return stopsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.stopSign
     *
     * @param stopsign the value for sys_userinfo.stopSign
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setStopsign(Boolean stopsign) {
        this.stopsign = stopsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userinfo.remark
     *
     * @return the value of sys_userinfo.remark
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userinfo.remark
     *
     * @param remark the value for sys_userinfo.remark
     *
     * @mbg.generated Wed Sep 18 13:44:51 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}